{% set version = "0.2.2" %}

package:
  name: cythongsl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/CythonGSL/CythonGSL-{{ version }}.tar.gz
  sha256: 9310ec565f4691fd20f49193744e76dae5b36b5f6460318009f8890cab0f58c6

build:
  number: 1002
  skip: True  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - gsl
  run:
    - python
    - gsl

test:
  imports:
    - cython_gsl

about:
  home: https://github.com/twiecki/CythonGSL
  license: GPL-3.0
  summary: CythonGSL provides a Cython interface for the GNU Scientific Library (GSL).

extra:
  recipe-maintainers:
    - twiecki
    - ocefpaf
