{% set version = "0.2.2" %}

package:
    name: cythongsl
    version: {{ version }}

source:
    fn: cythongsl-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/C/CythonGSL/CythonGSL-{{ version }}.tar.gz
    sha256: 9310ec565f4691fd20f49193744e76dae5b36b5f6460318009f8890cab0f58c6

build:
    number: 0
    skip: True  # [win]
    script: python setup.py install


requirements:
    build:
        - python
        - cython
        - gsl
    run:
        - python
        - gsl

test:
    imports:
        - cython_gsl

about:
    home: https://github.com/twiecki/CythonGSL
    license: GPL-3.0
    summary: CythonGSL provides a Cython interface for the GNU Scientific Library (GSL).

extra:
    recipe-maintainers:
        - twiecki
        - mmb90
        - ocefpaf
