travis:
  secure:
    BINSTAR_TOKEN: H9RDvarmbnhMpywjIwZj6RyyQnhVdFEp3DxNasCV0I5YF582kLY0tgElEL36wDmc06ehTGaCJCI8uK0E8q09d5xSlF8+BGI+TNQhJDocF2znvlMBl+B/WjS9htlVxYlcs+Z1f/6Axao4BQIVp6SeH2iDWciMBQG0LLjg+qVUjGUfTROEiVw2i5bOu376FOUIymAQtMbLvvZseONIJCxOOZwk6716hv5rWMhFfS64nn0CaLgVwt1EystMSjTJ7jp3P+xkOGQyBZBTISbY3Pk7vfPkrDtZ9rOAw/q57Py/TJ+OoyH1thZlqn7ZlSFTzSaTyUb6fsqmy8K19zyfpduDY7zxbjFZ/wsWfhWm8YBVN8Uybe9p32fktEjVEr/kwvYsBj7wmK3Uuat1TtSSvoTT2DA7jiBjAO8M8/bfuZl8P1bQEJOXwg3W5hgBkI0468V01Ko1VBNNBz1MEdXbU8o7fi5zO9IXalqIUTqN+NLmorzM/ietqrX7H+QP9fZ4AYItoMEW44xp2fDVCsTBN9wyjlVm4wy8Hkj8LuL3WtupoXX+c95kbiUAA4YQU8W8hd/lSQQAXkp+lYIru80/wb9cPwxz1nMnLHFa/aR+IKID/nTY2E9R9sU0NkysI0V3WBpp09m909NBrtQ82CXUgXlLmDhVJvDhOR1qOpl7nMCE4u8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
